// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js 런타임과 동일하게 .env.local(vercel env pull 산출물)을 우선 로드
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // 이 설정은 CLI(migrate/seed) 전용 — 런타임은 src/server/db.ts의 어댑터가 DATABASE_URL 사용.
    // 마이그레이션은 커넥션 풀러(pgbouncer)를 우회해야 하므로 직결 URL(Neon UNPOOLED) 우선.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
